"""
IO endpoint configuration models.

Maps logical device functions (e.g. "illumination D1 shutter") to physical
controller channels (e.g. MCU port D1, or NI-DAQ port0/line2).

Each endpoint represents a single signal line: either digital (TTL) or analog (DAC/AO).
An illumination port typically has two endpoints: one analog (intensity) and one digital (shutter).

The configuration is loaded once at startup and determines which controller drives each signal.
"""

import logging
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, model_validator

logger = logging.getLogger(__name__)


class IOControllerType(str, Enum):
    MCU = "MCU"
    NIDAQ = "NIDAQ"
    SERIAL = "SERIAL"


class IOSignalType(str, Enum):
    DIGITAL = "digital"
    ANALOG = "analog"


class IODirection(str, Enum):
    OUTPUT = "output"
    INPUT = "input"


class IOEndpoint(BaseModel):
    """A single IO signal mapped to a physical controller channel.

    Attributes:
        name: Unique logical name (e.g. "illum_D1_shutter", "camera_trigger").
        controller: Which controller drives this signal.
        signal_type: Digital or analog.
        direction: Output or input.
        channel_id: Controller-specific channel identifier.
            MCU: "port:N" (illumination port), "dac:N" (DAC channel),
                 "pin:N" (GPIO), "trigger:N" (hardware trigger channel).
            NIDAQ: "aoN" (analog out), "portP/lineL" (digital out), "aiN" (analog in).
            SERIAL: "device_prefix:channel" (e.g. "coolled:A").
        role: Semantic tag for grouping ("shutter", "intensity", "camera_trigger",
              "af_laser", "piezo").
    """
    name: str = Field(..., min_length=1)
    controller: IOControllerType
    signal_type: IOSignalType
    direction: IODirection = IODirection.OUTPUT
    channel_id: str = Field(..., min_length=1)
    role: str = ""


class IOEndpointConfig(BaseModel):
    """Root configuration for all IO endpoints on a machine.

    Loaded from machine_configs/io_endpoints.yaml.  When absent, default endpoints
    mirroring legacy MCU-only wiring are generated by build_default_io_endpoint_config().
    """

    version: float = Field(1.0, description="Configuration format version")
    endpoints: List[IOEndpoint] = Field(default_factory=list)

    model_config = {"extra": "allow"}

    # --- lazy indices (not serialised) ----------------------------------------

    _by_name: Optional[Dict[str, IOEndpoint]] = None
    _by_role: Optional[Dict[str, List[IOEndpoint]]] = None

    def _build_indices(self) -> None:
        if self._by_name is not None:
            return
        self._by_name = {}
        self._by_role = {}
        for ep in self.endpoints:
            if ep.name in self._by_name:
                raise ValueError(f"Duplicate IO endpoint name: '{ep.name}'")
            self._by_name[ep.name] = ep
            self._by_role.setdefault(ep.role, []).append(ep)

    def get(self, name: str) -> Optional[IOEndpoint]:
        """Look up an endpoint by logical name."""
        self._build_indices()
        return self._by_name.get(name)

    def require(self, name: str) -> IOEndpoint:
        """Look up an endpoint; raise KeyError if missing."""
        ep = self.get(name)
        if ep is None:
            raise KeyError(f"No IO endpoint named '{name}'")
        return ep

    def get_by_role(self, role: str) -> List[IOEndpoint]:
        self._build_indices()
        return list(self._by_role.get(role, []))

    def get_all(self) -> List[IOEndpoint]:
        return list(self.endpoints)

    def get_controller_endpoints(self, controller: IOControllerType) -> List[IOEndpoint]:
        return [ep for ep in self.endpoints if ep.controller == controller]

    @model_validator(mode="after")
    def _validate_no_duplicates(self) -> "IOEndpointConfig":
        names = set()
        for ep in self.endpoints:
            if ep.name in names:
                raise ValueError(f"Duplicate IO endpoint name: '{ep.name}'")
            names.add(ep.name)
        return self


def build_default_io_endpoint_config() -> IOEndpointConfig:
    """Generate default IO endpoints that mirror legacy MCU-only wiring."""
    endpoints: List[IOEndpoint] = []

    for i in range(5):
        port = f"D{i + 1}"
        endpoints.append(IOEndpoint(
            name=f"illum_{port}_intensity",
            controller=IOControllerType.MCU,
            signal_type=IOSignalType.ANALOG,
            direction=IODirection.OUTPUT,
            channel_id=f"port:{i}",
            role="intensity",
        ))
        endpoints.append(IOEndpoint(
            name=f"illum_{port}_shutter",
            controller=IOControllerType.MCU,
            signal_type=IOSignalType.DIGITAL,
            direction=IODirection.OUTPUT,
            channel_id=f"port:{i}",
            role="shutter",
        ))

    endpoints.append(IOEndpoint(
        name="camera_trigger",
        controller=IOControllerType.MCU,
        signal_type=IOSignalType.DIGITAL,
        direction=IODirection.OUTPUT,
        channel_id="trigger:0",
        role="camera_trigger",
    ))
    endpoints.append(IOEndpoint(
        name="af_laser",
        controller=IOControllerType.MCU,
        signal_type=IOSignalType.DIGITAL,
        direction=IODirection.OUTPUT,
        channel_id="pin:15",
        role="af_laser",
    ))
    endpoints.append(IOEndpoint(
        name="piezo",
        controller=IOControllerType.MCU,
        signal_type=IOSignalType.ANALOG,
        direction=IODirection.OUTPUT,
        channel_id="dac:7",
        role="piezo",
    ))

    return IOEndpointConfig(version=1.0, endpoints=endpoints)
